<?php
    $paises = [
        'Albania',
        'Alemania',
        'Andorra',
        'Austria',
        'Bélgica',
        'Bosnia y Herzegovina',
        'Bulgaria',
        'Chipre',
        'Croacia',
        'Dinamarca',
        'Eslovaquia',
        'Eslovenia',
        'España',
        'Estonia',
        'Finlandia',
        'Francia',
        'Grecia',
        'Hungría',
        'Irlanda',
        'Islandia',
        'Italia',
        'Kosovo',
        'Letonia',
        'Liechtenstein',
        'Lituania',
        'Luxemburgo',
        'Macedonia del Norte',
        'Malta',
        'Moldavia',
        'Mónaco',
        'Montenegro',
        'Noruega',
        'Países Bajos',
        'Polonia',
        'Portugal',
        'Reino Unido',
        'República Checa',
        'Rumania',
        'Rusia',
        'San Marino',
        'Serbia',
        'Suecia',
        'Suiza',
        'Ucrania',
        'Vaticano',
    ];
?>